name: linter
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: "Linter"
      - uses: actions/checkout@v2
      - run: yarn install & yarn lint
