name: linter
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Linter
      run: yarn
